#! vim set filetype=yaml:
# ------------------------------
# Docker Compose file for D0X-K1t
# -------------------------------

---
version: '3.9'

services:
  server:
    container_name: d0x-k1t
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: d0x-k1t:local
    volumes:
      - ./doxkit.db:/srv/D0x-K1t-v2/doxkit.db
    ports:
      - 5000:5000
    expose:
      - 5000
    networks:
      d0xk1t:
        aliases:
          - d0xk1t-server
        ipv4_address: 172.25.0.1

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-box
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
      # - ./ngrok-logs:/var/log/ngrok-log
    ports:
      - 80:80
      - 4040:4040
    expose:
      - 4040
    networks:
      d0xk1t:
        aliases:
          - ngrok
        ipv4_address: 172.25.0.2

networks:
  d0xk1t:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/24"
          gateway: 172.25.0.254
